// Lista de editoriales predefinidas
export const PREDEFINED_EDITORIALS = [
  'Planeta',
  'Penguin Random House',
  'Alfaguara',
  'Tusquets',
  'Anagrama',
  'Seix Barral',
  'Destino',
  'Grijalbo',
  'Debolsillo',
  'Booket',
  'Austral',
  'Espasa',
  'Aguilar',
  'Alianza',
  'Cátedra',
  'Crítica',
  'Paidós',
  'Ariel',
  'Gedisa',
  'Herder',
  'RBA',
  'Ediciones B',
  'Suma de Letras',
  'Plaza & Janés',
  'Temas de Hoy',
  'Martínez Roca',
  'Océano',
  'Urano',
  'Siruela',
  'Acantilado',
  'Pre-Textos',
  'Hiperión',
  'Visor',
  'Renacimiento',
  'Valdemar',
  'Alba',
  'Nórdica',
  'Impedimenta',
  'Periférica',
  'Libros del Asteroide',
  'Sexto Piso',
  'Blackie Books',
  'Lumen',
  'Salamandra',
  'Montena',
  'Nube de Tinta',
  'Alfaguara Infantil',
  'SM',
  'Bruño',
  'Anaya',
  'Santillana',
  'Vicens Vives',
  'Oxford',
  'Cambridge',
  'McGraw-Hill',
  'Pearson',
  'Wiley',
  'Springer',
  'Elsevier',
  'MIT Press',
  'Harvard University Press',
  'Oxford University Press',
  'Cambridge University Press',
  'Princeton University Press',
  'Yale University Press',
  'Stanford University Press',
  'University of California Press',
  'University of Chicago Press',
  'Columbia University Press',
  'Cornell University Press',
  'Johns Hopkins University Press',
  'University of Pennsylvania Press',
  'Duke University Press',
  'University of North Carolina Press',
  'University of Texas Press',
  'University of Wisconsin Press',
  'University of Minnesota Press',
  'University of Illinois Press',
  'University of Michigan Press',
  'Indiana University Press',
  'Ohio State University Press',
  'Penn State University Press',
  'Rutgers University Press',
  'Temple University Press',
  'University of Massachusetts Press',
  'University of Nebraska Press',
  'University of Oklahoma Press',
  'University of Arizona Press',
  'University of New Mexico Press',
  'University of Utah Press',
  'University of Nevada Press',
  'University of Idaho Press',
  'University of Wyoming Press',
  'University of Montana Press',
  'University of North Dakota Press',
  'University of South Dakota Press',
  'University of Kansas Press',
  'University of Missouri Press',
  'University of Arkansas Press',
  'University of Mississippi Press',
  'University of Alabama Press',
  'University of Georgia Press',
  'University of South Carolina Press',
  'University of Tennessee Press',
  'University of Kentucky Press',
  'University of Virginia Press',
  'University of Maryland Press',
  'University of Delaware Press',
  'University of New Jersey Press',
  'University of Connecticut Press',
  'University of Rhode Island Press',
  'University of Vermont Press',
  'University of New Hampshire Press',
  'University of Maine Press',
  'Simon & Schuster',
  'HarperCollins',
  'Macmillan',
  'Hachette',
  'Scholastic',
  'Bloomsbury',
  'Faber & Faber',
  'Vintage',
  'Knopf',
  'Doubleday',
  'Crown',
  'Ballantine',
  'Bantam',
  'Dell',
  'Delacorte',
  'Anchor',
  'Pantheon',
  'Everyman\'s Library',
  'Modern Library',
  'Library of America',
  'Norton',
  'Houghton Mifflin',
  'Little, Brown',
  'Farrar, Straus and Giroux',
  'Grove Press',
  'Atlantic Monthly Press',
  'Basic Books',
  'PublicAffairs',
  'Perseus Books',
  'Da Capo Press',
  'Avalon',
  'Carroll & Graf',
  'Marlowe & Company',
  'Thunder\'s Mouth Press',
  'Nation Books',
  'Bold Type Books',
  'Twelve',
  'Grand Central',
  'Orbit',
  'Redhook',
  'Jimmy Patterson',
  'Little, Brown Books for Young Readers',
  'Poppy',
  'Hachette Books',
  'Center Street',
  'FaithWords',
  'Worthy',
  'Worthy Kids',
  'Worthy Inspired',
  'Worthy Publishing',
  'Worthy Books',
  'Worthy Press',
  'Worthy Media',
  'Worthy Publishing Group',
  'Worthy Publishing Company',
  'Worthy Publishing House',
  'Worthy Publishing Inc',
  'Worthy Publishing LLC',
  'Worthy Publishing Ltd',
  'Worthy Publishing Corp',
  'Worthy Publishing Co',
  'Worthy Publishing & Co',
  'Worthy Publishing and Company',
  'Worthy Publishing and Co',
  'Worthy Publishing and Company LLC',
  'Worthy Publishing and Company Ltd',
  'Worthy Publishing and Company Corp',
  'Worthy Publishing and Company Co',
  'Worthy Publishing and Company & Co',
  'Worthy Publishing and Company and Company',
  'Worthy Publishing and Company and Co',
  'Worthy Publishing and Company and Company LLC',
  'Worthy Publishing and Company and Company Ltd',
  'Worthy Publishing and Company and Company Corp',
  'Worthy Publishing and Company and Company Co',
  'Worthy Publishing and Company and Company & Co',
  'Worthy Publishing and Company and Company and Company',
  'Worthy Publishing and Company and Company and Co'
].sort();

// Función para obtener todas las editoriales únicas (predefinidas + existentes)
export const getAllEditorials = (existingEditorials: string[] = []): string[] => {
  const combined = [...PREDEFINED_EDITORIALS, ...existingEditorials];
  return [...new Set(combined)].filter(Boolean).sort();
};